package gui;


public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        contrapanel.setVisible(false);
        btnConsulta.setSelected(true);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupS = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        label_sesion = new javax.swing.JLabel();
        btnext = new javax.swing.JButton();
        userpanel = new javax.swing.JPanel();
        label_usuario = new javax.swing.JLabel();
        caja_usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        contrapanel = new javax.swing.JPanel();
        label_contraseña = new javax.swing.JLabel();
        caja_usuario1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnConsulta = new javax.swing.JRadioButton();
        btnSesion = new javax.swing.JRadioButton();
        labelbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_sesion.setBackground(new java.awt.Color(255, 255, 255));
        label_sesion.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        label_sesion.setForeground(new java.awt.Color(0, 0, 0));
        label_sesion.setText("INICIO DE SESIÓN");
        bg.add(label_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 207, 30));

        btnext.setBackground(new java.awt.Color(255, 145, 76));
        btnext.setIcon(new javax.swing.ImageIcon("C:\\Users\\HeilerGa\\Documents\\NetBeansProjects\\horario\\src\\main\\java\\resources\\forwad.png")); // NOI18N
        btnext.setText("Next");
        btnext.setBorder(null);
        btnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnextActionPerformed(evt);
            }
        });
        bg.add(btnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, -1, -1));

        userpanel.setBackground(new java.awt.Color(255, 145, 76));

        label_usuario.setBackground(new java.awt.Color(255, 255, 255));
        label_usuario.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        label_usuario.setForeground(new java.awt.Color(0, 0, 0));
        label_usuario.setText("Usuario");

        caja_usuario.setBackground(new java.awt.Color(255, 145, 76));
        caja_usuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        caja_usuario.setForeground(new java.awt.Color(102, 102, 102));
        caja_usuario.setText("Ingrese su numero de cedula");
        caja_usuario.setBorder(null);
        caja_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_usuarioActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout userpanelLayout = new javax.swing.GroupLayout(userpanel);
        userpanel.setLayout(userpanelLayout);
        userpanelLayout.setHorizontalGroup(
            userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caja_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userpanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        userpanelLayout.setVerticalGroup(
            userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(caja_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        bg.add(userpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 350, -1));

        contrapanel.setBackground(new java.awt.Color(255, 145, 76));

        label_contraseña.setBackground(new java.awt.Color(255, 255, 255));
        label_contraseña.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        label_contraseña.setForeground(new java.awt.Color(0, 0, 0));
        label_contraseña.setText("Contraseña");

        caja_usuario1.setBackground(new java.awt.Color(255, 145, 76));
        caja_usuario1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        caja_usuario1.setForeground(new java.awt.Color(102, 102, 102));
        caja_usuario1.setText("Ingrese su contraseña");
        caja_usuario1.setBorder(null);
        caja_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_usuario1ActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout contrapanelLayout = new javax.swing.GroupLayout(contrapanel);
        contrapanel.setLayout(contrapanelLayout);
        contrapanelLayout.setHorizontalGroup(
            contrapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contrapanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(contrapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caja_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contrapanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contrapanelLayout.setVerticalGroup(
            contrapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contrapanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(caja_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bg.add(contrapanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 350, 100));

        btnConsulta.setBackground(new java.awt.Color(255, 145, 76));
        btngroupS.add(btnConsulta);
        btnConsulta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnConsulta.setForeground(new java.awt.Color(0, 0, 0));
        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        bg.add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, -1));

        btnSesion.setBackground(new java.awt.Color(255, 145, 76));
        btngroupS.add(btnSesion);
        btnSesion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnSesion.setText("Sesion");
        btnSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesionActionPerformed(evt);
            }
        });
        bg.add(btnSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 80, 40));

        labelbg.setIcon(new javax.swing.ImageIcon("C:\\Users\\HeilerGa\\Documents\\NetBeansProjects\\horario\\src\\main\\java\\resources\\background-sesion.jpeg")); // NOI18N
        labelbg.setText("jLabel1");
        bg.add(labelbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caja_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_usuarioActionPerformed

    private void caja_usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_usuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_usuario1ActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        // TODO add your handling code here:
        
        
            contrapanel.setVisible(false);
     
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionActionPerformed
        // TODO add your handling code here:
        
        contrapanel.setVisible(!contrapanel.isVisible());
            
    
    }//GEN-LAST:event_btnSesionActionPerformed

    private void btnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnextActionPerformed
        // TODO add your handling code here:
        Admin admin = new Admin();
        admin.setVisible(true);
               
    }//GEN-LAST:event_btnextActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JRadioButton btnConsulta;
    private javax.swing.JRadioButton btnSesion;
    private javax.swing.JButton btnext;
    private javax.swing.ButtonGroup btngroupS;
    private javax.swing.JTextField caja_usuario;
    private javax.swing.JTextField caja_usuario1;
    private javax.swing.JPanel contrapanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_contraseña;
    private javax.swing.JLabel label_sesion;
    private javax.swing.JLabel label_usuario;
    private javax.swing.JLabel labelbg;
    private javax.swing.JPanel userpanel;
    // End of variables declaration//GEN-END:variables
}
